### PR TITLE
Updated spanish translation and added a new theme

### PR DESCRIPTION
**Pull request by Darkmet98**

### CODE REVIEW

**Comment by kavid** [comment]
[Desktop.zip](https://github.com/xy2iii/vitashell-themes/files/453965/Desktop.zip) 

chinese v0.91

**Comment by Darkmet98** [comment]
Fixed @xy2iii the unknown conflict xDDDD

**Comment by ghost** [comment]
@Darkmet98 you must fix the translation, there is just a one error: in update_question: "estA disponible" when it must be "está disponible".

**Comment by Darkmet98** [comment]
@Keizel thanks for notify my mistake ;)

**Pull request merged**
