### PR TITLE
Added fonts section and tools

### PR DESCRIPTION
**Pull request by littlebalup**
Next vitashell update will allow to use custom pgf fonts.  Fonts section opened with tools to make custom PGF plus some chinese fonts. 
See https://github.com/TheOfficialFloW/VitaShell/issues/87 and https://github.com/TheOfficialFloW/VitaShell/issues/108 for details.

### CODE REVIEW

**Comment by fox-john** [comment]
We wait for official update of VitaShell for Add this section, thanks for this information ;).

**Comment by littlebalup** [comment]
No problem. I'll let you update your readme.
A readme is also provided into the builder archive.

**Comment by xy2i** [comment]
You may want to move the PGF builder to a separate directory (something like /tools?) so that users wanting to get fonts will not be inconvenienced.

**Comment by littlebalup** [comment]
I'll let you manage that like you prefer

**Comment by fox-john** [comment]
Please move the PGF builder to a separate directory and create new pull request, it's easy for you. ;)

Thanks

**Pull request closed without merging**
